// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nest.proto

package com.xy;

public final class NestGen {
  private NestGen() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xy.NestGen.Nest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 i1 = 1;</code>
     */
    int getI1();

    /**
     * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
     */
    boolean hasS1();
    /**
     * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
     */
    com.xy.NestGen.SingleInt getS1();
    /**
     * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
     */
    com.xy.NestGen.SingleIntOrBuilder getS1OrBuilder();
  }
  /**
   * Protobuf type {@code com.xy.NestGen.Nest}
   */
  public  static final class Nest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xy.NestGen.Nest)
      NestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Nest.newBuilder() to construct.
    private Nest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Nest() {
      i1_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Nest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              i1_ = input.readInt32();
              break;
            }
            case 18: {
              com.xy.NestGen.SingleInt.Builder subBuilder = null;
              if (s1_ != null) {
                subBuilder = s1_.toBuilder();
              }
              s1_ = input.readMessage(com.xy.NestGen.SingleInt.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s1_);
                s1_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xy.NestGen.internal_static_com_xy_NestGen_Nest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xy.NestGen.internal_static_com_xy_NestGen_Nest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xy.NestGen.Nest.class, com.xy.NestGen.Nest.Builder.class);
    }

    public static final int I1_FIELD_NUMBER = 1;
    private int i1_;
    /**
     * <code>int32 i1 = 1;</code>
     */
    public int getI1() {
      return i1_;
    }

    public static final int S1_FIELD_NUMBER = 2;
    private com.xy.NestGen.SingleInt s1_;
    /**
     * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
     */
    public boolean hasS1() {
      return s1_ != null;
    }
    /**
     * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
     */
    public com.xy.NestGen.SingleInt getS1() {
      return s1_ == null ? com.xy.NestGen.SingleInt.getDefaultInstance() : s1_;
    }
    /**
     * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
     */
    public com.xy.NestGen.SingleIntOrBuilder getS1OrBuilder() {
      return getS1();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (i1_ != 0) {
        output.writeInt32(1, i1_);
      }
      if (s1_ != null) {
        output.writeMessage(2, getS1());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (i1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, i1_);
      }
      if (s1_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getS1());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xy.NestGen.Nest)) {
        return super.equals(obj);
      }
      com.xy.NestGen.Nest other = (com.xy.NestGen.Nest) obj;

      boolean result = true;
      result = result && (getI1()
          == other.getI1());
      result = result && (hasS1() == other.hasS1());
      if (hasS1()) {
        result = result && getS1()
            .equals(other.getS1());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + I1_FIELD_NUMBER;
      hash = (53 * hash) + getI1();
      if (hasS1()) {
        hash = (37 * hash) + S1_FIELD_NUMBER;
        hash = (53 * hash) + getS1().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xy.NestGen.Nest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xy.NestGen.Nest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xy.NestGen.Nest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xy.NestGen.Nest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xy.NestGen.Nest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xy.NestGen.Nest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xy.NestGen.Nest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xy.NestGen.Nest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xy.NestGen.Nest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xy.NestGen.Nest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xy.NestGen.Nest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xy.NestGen.Nest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xy.NestGen.Nest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xy.NestGen.Nest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xy.NestGen.Nest)
        com.xy.NestGen.NestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xy.NestGen.internal_static_com_xy_NestGen_Nest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xy.NestGen.internal_static_com_xy_NestGen_Nest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xy.NestGen.Nest.class, com.xy.NestGen.Nest.Builder.class);
      }

      // Construct using com.xy.NestGen.Nest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        i1_ = 0;

        if (s1Builder_ == null) {
          s1_ = null;
        } else {
          s1_ = null;
          s1Builder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xy.NestGen.internal_static_com_xy_NestGen_Nest_descriptor;
      }

      public com.xy.NestGen.Nest getDefaultInstanceForType() {
        return com.xy.NestGen.Nest.getDefaultInstance();
      }

      public com.xy.NestGen.Nest build() {
        com.xy.NestGen.Nest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xy.NestGen.Nest buildPartial() {
        com.xy.NestGen.Nest result = new com.xy.NestGen.Nest(this);
        result.i1_ = i1_;
        if (s1Builder_ == null) {
          result.s1_ = s1_;
        } else {
          result.s1_ = s1Builder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xy.NestGen.Nest) {
          return mergeFrom((com.xy.NestGen.Nest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xy.NestGen.Nest other) {
        if (other == com.xy.NestGen.Nest.getDefaultInstance()) return this;
        if (other.getI1() != 0) {
          setI1(other.getI1());
        }
        if (other.hasS1()) {
          mergeS1(other.getS1());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xy.NestGen.Nest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xy.NestGen.Nest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int i1_ ;
      /**
       * <code>int32 i1 = 1;</code>
       */
      public int getI1() {
        return i1_;
      }
      /**
       * <code>int32 i1 = 1;</code>
       */
      public Builder setI1(int value) {
        
        i1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i1 = 1;</code>
       */
      public Builder clearI1() {
        
        i1_ = 0;
        onChanged();
        return this;
      }

      private com.xy.NestGen.SingleInt s1_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xy.NestGen.SingleInt, com.xy.NestGen.SingleInt.Builder, com.xy.NestGen.SingleIntOrBuilder> s1Builder_;
      /**
       * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
       */
      public boolean hasS1() {
        return s1Builder_ != null || s1_ != null;
      }
      /**
       * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
       */
      public com.xy.NestGen.SingleInt getS1() {
        if (s1Builder_ == null) {
          return s1_ == null ? com.xy.NestGen.SingleInt.getDefaultInstance() : s1_;
        } else {
          return s1Builder_.getMessage();
        }
      }
      /**
       * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
       */
      public Builder setS1(com.xy.NestGen.SingleInt value) {
        if (s1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s1_ = value;
          onChanged();
        } else {
          s1Builder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
       */
      public Builder setS1(
          com.xy.NestGen.SingleInt.Builder builderForValue) {
        if (s1Builder_ == null) {
          s1_ = builderForValue.build();
          onChanged();
        } else {
          s1Builder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
       */
      public Builder mergeS1(com.xy.NestGen.SingleInt value) {
        if (s1Builder_ == null) {
          if (s1_ != null) {
            s1_ =
              com.xy.NestGen.SingleInt.newBuilder(s1_).mergeFrom(value).buildPartial();
          } else {
            s1_ = value;
          }
          onChanged();
        } else {
          s1Builder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
       */
      public Builder clearS1() {
        if (s1Builder_ == null) {
          s1_ = null;
          onChanged();
        } else {
          s1_ = null;
          s1Builder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
       */
      public com.xy.NestGen.SingleInt.Builder getS1Builder() {
        
        onChanged();
        return getS1FieldBuilder().getBuilder();
      }
      /**
       * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
       */
      public com.xy.NestGen.SingleIntOrBuilder getS1OrBuilder() {
        if (s1Builder_ != null) {
          return s1Builder_.getMessageOrBuilder();
        } else {
          return s1_ == null ?
              com.xy.NestGen.SingleInt.getDefaultInstance() : s1_;
        }
      }
      /**
       * <code>.com.xy.NestGen.SingleInt s1 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.xy.NestGen.SingleInt, com.xy.NestGen.SingleInt.Builder, com.xy.NestGen.SingleIntOrBuilder> 
          getS1FieldBuilder() {
        if (s1Builder_ == null) {
          s1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.xy.NestGen.SingleInt, com.xy.NestGen.SingleInt.Builder, com.xy.NestGen.SingleIntOrBuilder>(
                  getS1(),
                  getParentForChildren(),
                  isClean());
          s1_ = null;
        }
        return s1Builder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xy.NestGen.Nest)
    }

    // @@protoc_insertion_point(class_scope:com.xy.NestGen.Nest)
    private static final com.xy.NestGen.Nest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xy.NestGen.Nest();
    }

    public static com.xy.NestGen.Nest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Nest>
        PARSER = new com.google.protobuf.AbstractParser<Nest>() {
      public Nest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Nest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Nest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Nest> getParserForType() {
      return PARSER;
    }

    public com.xy.NestGen.Nest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SingleIntOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xy.NestGen.SingleInt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 i1 = 1;</code>
     */
    int getI1();
  }
  /**
   * Protobuf type {@code com.xy.NestGen.SingleInt}
   */
  public  static final class SingleInt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xy.NestGen.SingleInt)
      SingleIntOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SingleInt.newBuilder() to construct.
    private SingleInt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SingleInt() {
      i1_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SingleInt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              i1_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xy.NestGen.internal_static_com_xy_NestGen_SingleInt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xy.NestGen.internal_static_com_xy_NestGen_SingleInt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xy.NestGen.SingleInt.class, com.xy.NestGen.SingleInt.Builder.class);
    }

    public static final int I1_FIELD_NUMBER = 1;
    private int i1_;
    /**
     * <code>int32 i1 = 1;</code>
     */
    public int getI1() {
      return i1_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (i1_ != 0) {
        output.writeInt32(1, i1_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (i1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, i1_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xy.NestGen.SingleInt)) {
        return super.equals(obj);
      }
      com.xy.NestGen.SingleInt other = (com.xy.NestGen.SingleInt) obj;

      boolean result = true;
      result = result && (getI1()
          == other.getI1());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + I1_FIELD_NUMBER;
      hash = (53 * hash) + getI1();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xy.NestGen.SingleInt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xy.NestGen.SingleInt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xy.NestGen.SingleInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xy.NestGen.SingleInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xy.NestGen.SingleInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xy.NestGen.SingleInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xy.NestGen.SingleInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xy.NestGen.SingleInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xy.NestGen.SingleInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xy.NestGen.SingleInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xy.NestGen.SingleInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xy.NestGen.SingleInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xy.NestGen.SingleInt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xy.NestGen.SingleInt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xy.NestGen.SingleInt)
        com.xy.NestGen.SingleIntOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xy.NestGen.internal_static_com_xy_NestGen_SingleInt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xy.NestGen.internal_static_com_xy_NestGen_SingleInt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xy.NestGen.SingleInt.class, com.xy.NestGen.SingleInt.Builder.class);
      }

      // Construct using com.xy.NestGen.SingleInt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        i1_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xy.NestGen.internal_static_com_xy_NestGen_SingleInt_descriptor;
      }

      public com.xy.NestGen.SingleInt getDefaultInstanceForType() {
        return com.xy.NestGen.SingleInt.getDefaultInstance();
      }

      public com.xy.NestGen.SingleInt build() {
        com.xy.NestGen.SingleInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xy.NestGen.SingleInt buildPartial() {
        com.xy.NestGen.SingleInt result = new com.xy.NestGen.SingleInt(this);
        result.i1_ = i1_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xy.NestGen.SingleInt) {
          return mergeFrom((com.xy.NestGen.SingleInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xy.NestGen.SingleInt other) {
        if (other == com.xy.NestGen.SingleInt.getDefaultInstance()) return this;
        if (other.getI1() != 0) {
          setI1(other.getI1());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xy.NestGen.SingleInt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xy.NestGen.SingleInt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int i1_ ;
      /**
       * <code>int32 i1 = 1;</code>
       */
      public int getI1() {
        return i1_;
      }
      /**
       * <code>int32 i1 = 1;</code>
       */
      public Builder setI1(int value) {
        
        i1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i1 = 1;</code>
       */
      public Builder clearI1() {
        
        i1_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xy.NestGen.SingleInt)
    }

    // @@protoc_insertion_point(class_scope:com.xy.NestGen.SingleInt)
    private static final com.xy.NestGen.SingleInt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xy.NestGen.SingleInt();
    }

    public static com.xy.NestGen.SingleInt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SingleInt>
        PARSER = new com.google.protobuf.AbstractParser<SingleInt>() {
      public SingleInt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SingleInt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SingleInt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SingleInt> getParserForType() {
      return PARSER;
    }

    public com.xy.NestGen.SingleInt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xy_NestGen_Nest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xy_NestGen_Nest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xy_NestGen_SingleInt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xy_NestGen_SingleInt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnest.proto\022\016com.xy.NestGen\"9\n\004Nest\022\n\n\002" +
      "i1\030\001 \001(\005\022%\n\002s1\030\002 \001(\0132\031.com.xy.NestGen.Si" +
      "ngleInt\"\027\n\tSingleInt\022\n\n\002i1\030\001 \001(\005B\023\n\006com." +
      "xyB\007NestGenP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xy_NestGen_Nest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xy_NestGen_Nest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xy_NestGen_Nest_descriptor,
        new java.lang.String[] { "I1", "S1", });
    internal_static_com_xy_NestGen_SingleInt_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xy_NestGen_SingleInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xy_NestGen_SingleInt_descriptor,
        new java.lang.String[] { "I1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
