// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: twoint.proto

package com.xy;

public final class TwoIntGen {
  private TwoIntGen() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TwoIntOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.xy.TwoIntGen.TwoInt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 i1 = 1;</code>
     */
    int getI1();

    /**
     * <code>int32 i2 = 2;</code>
     */
    int getI2();
  }
  /**
   * Protobuf type {@code com.xy.TwoIntGen.TwoInt}
   */
  public  static final class TwoInt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.xy.TwoIntGen.TwoInt)
      TwoIntOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TwoInt.newBuilder() to construct.
    private TwoInt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TwoInt() {
      i1_ = 0;
      i2_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TwoInt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              i1_ = input.readInt32();
              break;
            }
            case 16: {

              i2_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xy.TwoIntGen.internal_static_com_xy_TwoIntGen_TwoInt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xy.TwoIntGen.internal_static_com_xy_TwoIntGen_TwoInt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xy.TwoIntGen.TwoInt.class, com.xy.TwoIntGen.TwoInt.Builder.class);
    }

    public static final int I1_FIELD_NUMBER = 1;
    private int i1_;
    /**
     * <code>int32 i1 = 1;</code>
     */
    public int getI1() {
      return i1_;
    }

    public static final int I2_FIELD_NUMBER = 2;
    private int i2_;
    /**
     * <code>int32 i2 = 2;</code>
     */
    public int getI2() {
      return i2_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (i1_ != 0) {
        output.writeInt32(1, i1_);
      }
      if (i2_ != 0) {
        output.writeInt32(2, i2_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (i1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, i1_);
      }
      if (i2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, i2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xy.TwoIntGen.TwoInt)) {
        return super.equals(obj);
      }
      com.xy.TwoIntGen.TwoInt other = (com.xy.TwoIntGen.TwoInt) obj;

      boolean result = true;
      result = result && (getI1()
          == other.getI1());
      result = result && (getI2()
          == other.getI2());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + I1_FIELD_NUMBER;
      hash = (53 * hash) + getI1();
      hash = (37 * hash) + I2_FIELD_NUMBER;
      hash = (53 * hash) + getI2();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xy.TwoIntGen.TwoInt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xy.TwoIntGen.TwoInt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xy.TwoIntGen.TwoInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xy.TwoIntGen.TwoInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xy.TwoIntGen.TwoInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xy.TwoIntGen.TwoInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xy.TwoIntGen.TwoInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xy.TwoIntGen.TwoInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xy.TwoIntGen.TwoInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xy.TwoIntGen.TwoInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xy.TwoIntGen.TwoInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xy.TwoIntGen.TwoInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xy.TwoIntGen.TwoInt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xy.TwoIntGen.TwoInt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.xy.TwoIntGen.TwoInt)
        com.xy.TwoIntGen.TwoIntOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xy.TwoIntGen.internal_static_com_xy_TwoIntGen_TwoInt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xy.TwoIntGen.internal_static_com_xy_TwoIntGen_TwoInt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xy.TwoIntGen.TwoInt.class, com.xy.TwoIntGen.TwoInt.Builder.class);
      }

      // Construct using com.xy.TwoIntGen.TwoInt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        i1_ = 0;

        i2_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xy.TwoIntGen.internal_static_com_xy_TwoIntGen_TwoInt_descriptor;
      }

      public com.xy.TwoIntGen.TwoInt getDefaultInstanceForType() {
        return com.xy.TwoIntGen.TwoInt.getDefaultInstance();
      }

      public com.xy.TwoIntGen.TwoInt build() {
        com.xy.TwoIntGen.TwoInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xy.TwoIntGen.TwoInt buildPartial() {
        com.xy.TwoIntGen.TwoInt result = new com.xy.TwoIntGen.TwoInt(this);
        result.i1_ = i1_;
        result.i2_ = i2_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xy.TwoIntGen.TwoInt) {
          return mergeFrom((com.xy.TwoIntGen.TwoInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xy.TwoIntGen.TwoInt other) {
        if (other == com.xy.TwoIntGen.TwoInt.getDefaultInstance()) return this;
        if (other.getI1() != 0) {
          setI1(other.getI1());
        }
        if (other.getI2() != 0) {
          setI2(other.getI2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xy.TwoIntGen.TwoInt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xy.TwoIntGen.TwoInt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int i1_ ;
      /**
       * <code>int32 i1 = 1;</code>
       */
      public int getI1() {
        return i1_;
      }
      /**
       * <code>int32 i1 = 1;</code>
       */
      public Builder setI1(int value) {
        
        i1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i1 = 1;</code>
       */
      public Builder clearI1() {
        
        i1_ = 0;
        onChanged();
        return this;
      }

      private int i2_ ;
      /**
       * <code>int32 i2 = 2;</code>
       */
      public int getI2() {
        return i2_;
      }
      /**
       * <code>int32 i2 = 2;</code>
       */
      public Builder setI2(int value) {
        
        i2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i2 = 2;</code>
       */
      public Builder clearI2() {
        
        i2_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.xy.TwoIntGen.TwoInt)
    }

    // @@protoc_insertion_point(class_scope:com.xy.TwoIntGen.TwoInt)
    private static final com.xy.TwoIntGen.TwoInt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xy.TwoIntGen.TwoInt();
    }

    public static com.xy.TwoIntGen.TwoInt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TwoInt>
        PARSER = new com.google.protobuf.AbstractParser<TwoInt>() {
      public TwoInt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TwoInt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TwoInt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TwoInt> getParserForType() {
      return PARSER;
    }

    public com.xy.TwoIntGen.TwoInt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xy_TwoIntGen_TwoInt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xy_TwoIntGen_TwoInt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014twoint.proto\022\020com.xy.TwoIntGen\" \n\006TwoI" +
      "nt\022\n\n\002i1\030\001 \001(\005\022\n\n\002i2\030\002 \001(\005B\025\n\006com.xyB\tTw" +
      "oIntGenP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_xy_TwoIntGen_TwoInt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xy_TwoIntGen_TwoInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xy_TwoIntGen_TwoInt_descriptor,
        new java.lang.String[] { "I1", "I2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
